[project]
name = "ferro-dashboard"
version = "0.1.0"
dependencies = [
    "dash",
    "dash-leaflet",
    "pandas",
    "geopandas",
    "shapely",
    "pyproj",
	"plotly",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"